INSERT INTO avl_categories (
    categoryID,
    name,
    parent,
    products_count,
    description,
    picture,
    products_count_admin,
    sort_order,
    viewed_times,
    allow_products_comparison,
    allow_products_search,
    show_subcategories_products,
    meta_description,
    meta_keywords,
    title
  )
VALUES (
    categoryID:int,
    'name:varchar',
    parent:int,
    products_count:int,
    'description:text',
    'picture:varchar',
    products_count_admin:int,
    sort_order:int,
    viewed_times:int,
    allow_products_comparison:int,
    allow_products_search:int,
    show_subcategories_products:int,
    'meta_description:text',
    'meta_keywords:text',
    'title:text'
  );